### PR TITLE
added box to choose-your-cause

### PR DESCRIPTION
**Pull request by neilgoodridge**
Updated the cause index page. 

1. Added box around 'Choose a cause you care about' and resized to fit
2. Made the 'take action' button position remain the same despite the button above dropping down when selecting.

This was achieved by moving the 'submit-container' div outside of the 'choose' div (which is the main div of the page body). This meant that applying a 'position: absolute; to the button inside the 'position: relative;' of the container it's in allowed me to fix its position.

https://user-images.githubusercontent.com/76408528/123178091-6aefcb80-d47e-11eb-888f-0acc638f7975.mp4

### CODE REVIEW

**Comment by awalsh3** [comment]
This looks great! I just noticed the time buttons do not have the same spacing between each button. I'll add it to the list

**Comment by neilgoodridge** [comment]
I'll get on that. Previously the text in the buttons was off-center, and when centering the text, the buttons moved by the equivalent pixels (note it's the single digit buttons that aren't right while the double digit ones are fine. I'll try and resolve that quickly.

**Comment by awalsh3** [comment]
Do you want to do it in this branch and then I'll merge the whole thing when you're done?

**Comment by neilgoodridge** [comment]
Yes. I've now done that and re-committed.

**Comment by awalsh3** [comment]
Reviewing now!

**Comment by awalsh3** [comment]
Screen Shot 2021-06-24 at 11 25 07
Screen Shot 2021-06-24 at 11 24 57

**Comment by awalsh3** [comment]
Weirdly, depending on the size it displays it like the photos above in chrome at 67% and 75%. Merging anyways since we will be presenting from your computer? Or are we presenting from @lucien-george's and need to sort out if it will look like this on his as well?

**Comment by lucien-george** [comment]
> Weirdly, depending on the size it displays it like the photos above in chrome at 67% and 75%. Merging anyways since we will be presenting from your computer? Or are we presenting from @lucien-george's and need to sort out if it will look like this on his as well?

Since you guys are on campus you will be presenting from a 13" screen size. We can test it tonight after the practice demos of the last 4 teams if you want 👌

**Comment by awalsh3** [comment]
> > Weirdly, depending on the size it displays it like the photos above in chrome at 67% and 75%. Merging anyways since we will be presenting from your computer? Or are we presenting from @lucien-george's and need to sort out if it will look like this on his as well?
> 
> Since you guys are on campus you will be presenting from a 13" screen size. We can test it tonight after the practice demos of the last 4 teams if you want 👌

That would be great, thank you!

**Pull request merged**
